networks:
  vhub-network:
    driver: bridge

volumes:
  vhub-ua-postgres-data:

services:
  vhub-ua-host:
    container_name: vhub-user-activities-host
    build:
      dockerfile: Dockerfile
    image: vhub-user-activities-app:1.0
    ports:
      - "2000:80"
    networks:
      - vhub-network
    volumes:
      - ./Vhub.UserActivities.Host/appsettings.json:/app/appsettings.json
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:80
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      vhub-ua-db:
        condition: service_healthy
      vhub-ua-db-migration:
        condition: service_completed_successfully

  vhub-ua-db:
    image: postgres:15
    restart: unless-stopped
    container_name: vhub-ua-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "vhub-ua-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGUSER: "postgres"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
      - vhub-ua-postgres-data:/var/lib/postgresql/data
    networks:
      - vhub-network

  vhub-ua-db-migration:
    build:
      context: ./VHub.UserActivities.Database.Migrations
      dockerfile: Dockerfile
    image: vhub-ua-db-migration:1.0
    container_name: vhub-ua-db-migration
    depends_on:
      vhub-ua-db:
        condition: service_healthy
    environment:
      ConnectionStrings__vhub-ua-service-db-connection: User ID=postgres;Password=postgres;Host=vhub-ua-db;Port=5432;Database=vhub-ua-db;
    networks:
      - vhub-network